fixtures_documentation:
    path:     /fixtures/doc
    methods : [GET]
    defaults: { _controller: FixturesDocumentation\Controller\FixtureDocumentationController:generateDocumentationAction }

fixtures_reload:
    path:     /fixtures/reload
    methods : [GET]
    defaults: { _controller: FixturesDocumentation\Controller\FixtureDocumentationController:reloadAction }
