services:
    # Controllers
    FixturesDocumentation\Controller\FixturesDocumentationController:
        public: true
        autowire: true
        arguments:
            $docTitle: '%fixtures_documentation.title%'
            $reloadCommands: '%fixtures_documentation.reloadCommands%'

    # Managers
    FixturesDocumentation\Service\FixturesDocumentationManager:
        public: true
        autowire: true
        arguments:
            $projectDir: '%kernel.project_dir%'
            $reloadCommands: '%fixtures_documentation.reloadCommands%'

    # Listeners
    FixturesDocumentation\EventListener\FixturesDocumentationListener:
        public: true
        arguments:
            - '@FixturesDocumentation\Service\FixturesDocumentationManager'
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandExecution }
            - { name: kernel.event_listener, event: console.terminate, method: onTerminateExecution }
